# core/events.py
from dataclasses import dataclass
from enum import Enum, auto
from typing import Optional
from datetime import datetime

class EventType(Enum):
    MARKET = auto()   # New market data arrived (tick or bar)
    SIGNAL = auto()   # Strategy generated a trading signal
    ORDER = auto()    # Risk manager approved an order to be sent to broker
    FILL = auto()     # Broker confirmed the order was filled

class Event:
    """Base class for all events."""
    pass

@dataclass
class MarketEvent(Event):
    """Handles the receipt of new market data."""
    symbol: str
    timestamp: datetime
    bid: float
    ask: float
    type: EventType = EventType.MARKET

@dataclass
class SignalEvent(Event):
    """Generated by a Strategy when a trading opportunity is found."""
    symbol: str
    timestamp: datetime
    signal_type: str  # "LONG", "SHORT", or "EXIT"
    strength: float   # Confidence level from 0.0 to 1.0
    type: EventType = EventType.SIGNAL

@dataclass
class OrderEvent(Event):
    """Generated after a Signal passes the Risk Management filters."""
    symbol: str
    order_type: str   # "MARKET", "LIMIT", "STOP"
    quantity: float
    direction: str    # "BUY" or "SELL"
    price: Optional[float] = None
    type: EventType = EventType.ORDER

@dataclass
class FillEvent(Event):
    """Stores the actual fill details returned from the brokerage."""
    symbol: str
    timestamp: datetime
    quantity: float
    direction: str
    fill_price: float
    exchange: str
    commission: float
    type: EventType = EventType.FILL